In [112]:
import numpy as np
import matplotlib.pyplot as plt
import voters
import elections

import importlib

In [267]:
importlib.reload(voters)
importlib.reload(elections)
from voters import gen_voters, calc_distance_tensor, calc_distance_matrix
from elections import Borda, IRV, Election

In [261]:
V = gen_voters(10,3)
C = gen_voters(3,3)

In [127]:
D = calc_distance_matrix(V,C)

In [176]:
P = np.array(D.argsort(axis=1),dtype=object)

In [152]:
P.sum(axis=0)

array([15, 7, 8], dtype=object)

In [206]:
A = ['Alice', 'Bob', 'Charlie']

In [256]:
Borda(P, A).run()

array([ 8,  7, 15])

In [257]:
A[IRV(P,A).run()]

'Charlie'

In [235]:
np.zeros()

array([[2, 1, 0],
       [2, 0, 1],
       [0, 1, 2],
       [1, 2, 0],
       [2, 1, 0],
       [0, 1, 2],
       [2, 0, 1],
       [2, 1, 0],
       [2, 0, 1],
       [2, 0, 1]], dtype=object)

In [239]:
np.argsort([4,2,3])

array([1, 2, 0], dtype=int64)

In [243]:
np.arange(d-1,-1,-1)

array([2, 1, 0])

In [251]:
R = np.unique([4,2,3], return_counts=True)

In [252]:
R

(array([2, 3, 4]), array([1, 1, 1], dtype=int64))

In [269]:
E = Election(V, C)
E.preprocess()

In [272]:
E.dist_to_alt(2) 

2.136042357039994